<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
    <url>
        <loc>https://mindthecode.com/</loc>
        <lastmod>2021-02-07T16:26:28+00:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://mindthecode.com/about/</loc>
        <lastmod>2021-02-07T16:26:29+00:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://mindthecode.com/archive</loc>
        <lastmod>2021-02-07T16:26:29+00:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://mindthecode.com/archive/</loc>
        <lastmod>2021-02-07T16:26:29+00:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://mindthecode.com/blog/a-more-colourful-cat-in-your-shell/</loc>
        <lastmod>2021-02-07T16:26:29+00:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
</urlset>
