# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /blog/:title

# Setup
title: "Mindthecode"
description: "Stef van den Ham writes about web"
url: https://mindthecode.com
baseurl: "/"
logo: "favicon.png"

author:
  name: "Stef van den Jam"

# Custom vars
twitter: https://twitter.com/hyra
github: https://github.com/hyra

jekyll_analytics:
  GoogleAnalytics:
    id: UA-40203772-4
    anonymizeIp: false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-analytics
